* OMMIR - lib for symbolic musical feature extraction
** PITCH STATISTICS

     P-1 Basic Pitch Histogram: A feature vector consisting of bin
     magnitudes of the basic pitch histogram described above. Each bin
     corresponds to one of the 128 MIDI pitches, ordered from lowest
     to highest, and with an interval of a semitone between each
     (enharmonic equivalents are assigned the same pitch number). Bin
     60 corresponds to middle C. The magnitude of of each bin is
     proportional to the the number of times notes occurred at the
     bin's pitch in the piece, relative to all other pitches in the
     piece (the histogram is normalized).

     P-2 Pitch Class Histogram: A feature vector consisting of bin magnitudes of the pitch class histogram described above. Each bin corresponds to one of the 12 pitch classes, ordered in increasing pitch with an interval of a semitone between each (enharmonic equivalents are assigned the same pitch class number). The first bin corresponds to the most common pitch class in the piece under consideration (it does NOT correspond to a set pitch class). The magnitude of of each bin is proportional to the the number of times notes occurred at the bin's pitch class in the piece, relative to all other pitch classes in the piece (the histogram is normalized).

     P-3 Folded Fifths Pitch Class Histogram: A feature vector consisting of bin magnitudes of the folded fifths pitch class histogram described above. Each bin corresponds to one of the 12 pitch classes, and the bins are ordered such that adjacent bins are separated by an ascending perfect fifth. Bin 0 corresponds to C. Enharmonic equivalents are assigned the same pitch class number. The magnitude of of each bin is proportional to the the number of times notes occurred at the bin's pitch class in the piece, relative to all other pitch classes in the piece (the histogram is normalized).

     P-4 Prevalence of Most Common Pitch: Fraction of notes that correspond to
     the most common pitch.

     P-5 Prevalence of Most Common Pitch Class: Fraction of notes that
     correspond to the most common pitch class.

     P-6 Relative Prevalence of Top Pitches: Relative frequency of the second
     most common pitch in the piece, divided by the relative frequency of the
     most common pitch.

     P-7 Relative Prevalence of Top Pitch Classes: Relative frequency of the of
     the second most common pitch class in the piece, divided by the relative
     frequency of the most common pitch class.

     P-8 Interval Between Most Prevalent Pitches: Absolute value of the
     difference (in semitones) between the pitches of the two most frequently
     occurring pitches.

     P-9 Interval Between Most Prevalent Pitch Classes: Absolute value of the
     difference (in semitones) between the pitches of the two most frequently
     occurring pitch classes.

     P-10 Number of Common Pitches: Number of pitches that account individually
     for at least 9% of all notes. Enharmonic equivalents are grouped together
     for the purpose of this calculation.

     P-11 Pitch Variety: Number of pitches that occur at least once in the
     piece. Enharmonic equivalents are grouped together for the purpose of this
     calculation.

     P-12 Pitch Class Variety: Number of pitch classes that occur at
     least once in the piece. Enharmonic equivalents are grouped
     together for the purpose of this calculation.

     P-13 Range: Difference in semitones between the highest and
     lowest pitches.

     P-14 Most Common Pitch: MIDI pitch value of the most frequently occurring pitch.
     P-15 Mean Pitch: Mean MIDI pitch value, averaged across all pitched notes in the piece. Set to 0 if there are no pitched notes.
     P-16 Importance of Bass Register: Fraction of notes between MIDI pitches 0 and 54.
     P-17 Importance of Middle Register: Fraction of notes between MIDI pitches 55 and 72.
     P-18 Importance of High Register: Fraction of notes between MIDI pitches 73 and 127.
     P-19 Most Common Pitch Class: The pitch class that occurs most frequently compared to other pitch classes. A value of 0 corresponds to C, and pitches increase chromatically by semitone in integer units (e.g. a value of 2 would mean that D is the most common pitch class). Enharmonic equivalents are treated as a single pitch class.
     P-20 Dominant Spread: Largest number of consecutive pitch classes separated by perfect 5ths that each individually account for at least 9% of the total notes in the piece.
     P-21 Strong Tonal Centres: Number of isolated peaks in the fifths pitch histogram that each individually account for at least 9% of all notes in the piece.
     P-22 Major or Minor: Whether the piece is major or minor, as indicated by the first encountered major/minor metadata tag in the piece. Set to 0 if the metadata indicates that the piece is major, or set to 1 if the metadata indicates that it is minor. Defaults to 0 if the key signature is unknown.
     P-23 Glissando Prevalence: Number of pitched MIDI Note Ons that have at least one MIDI Pitch Bend associated with them, divided by the total number of pitched Note Ons in the piece.
     P-24 Average Range of Glissandos: Average range of MIDI Pitch Bends, where "range" is defined as the greatest value of the absolute difference between 64 and the second data byte of all MIDI Pitch Bend messages falling between the Note On and Note Off messages of any note in the piece. Set to 0 if there are no MIDI Pitch Bends in the piece.
     P-25 Vibrato Prevalence: Number of pitched notes that have associated MIDI Pitch Bend messages change direction at least twice in connection with the note in question, divided by the total number of pitched Note Ons in the piece.
     P-26 Microtone Prevalence: Number of pitched notes that are each associated with exactly one MIDI Pitch Bend message, divided by the total number of pitched Note Ons in the piece. Set to 0 if there are no pitched Note Ons in the piece.

** MELODIC FEATURES


 Features related to melody and melodic intervals:

     M-1 Melodic Interval Histogram: A feature vector consisting of the bin magnitudes of the melodic interval histogram described above. Each bin corresponds to a melodic interval, and the bin index indicates the number of semitones comprising the interval associated with the bin (there are 128 bins in all). For example, bin 0 corresponds to repeated pitches, bin 1 to a melodic interval of one semitone, bin 2 to a melodic interval of 2 semitones, etc. The magnitude of each bin is proportional to the fraction of melodic intervals in the piece that are of the kind associated with the bin (this histogram is normalized). Rising and falling intervals are treated as identical. Melodies are assumed to be contained within individual MIDI tracks and channels, so melodic intervals are found separately for each track and channel before being combined in this histogram. It is also assumed that there is only one melody at a time per MIDI channel (if multiple notes occur simultaneously on the same MIDI tick on the same MIDI track and channel, then all notes but the first note on that tick are ignored). Other than this, all notes on the same track and the same channel are treated as if they are part of a single melody. It is also assumed that melodies do not cross MIDI tracks or channels (i.e. that they are each separately contained in their own track and channel). Only pitched notes are considered, so all notes on the unpitched MIDI Channel 10 are ignored.
     M-2 Most Common Melodic Interval: Number of semitones corresponding to the most frequently occurring melodic interval.
     M-3 Mean Melodic Interval: Mean average (in semitones) of the intervals involved in each of the melodic intervals in the piece.
     M-4 Number of Common Melodic Intervals: Number of different melodic intervals that each account individually for at least 9% of all melodic intervals.
     M-5 Distance Between Most Prevalent Melodic Intervals: Absolute value of the difference (in semitones) between the most common and second most common melodic intervals in the piece.
     M-6 Prevalence of Most Common Melodic Interval: Fraction of all melodic intervals that corresponds to the most common melodic interval.
     M-7 Relative Prevalence of Most Common Melodic Intervals: Relative frequency of the second most common melodic interval in the piece, divided by the relative frequency of the most common melodic interval.
     M-8 Amount of Arpeggiation: Fraction of melodic intervals that are repeated notes, minor thirds, major thirds, perfect fifths, minor sevenths, major sevenths, octaves, minor tenths or major tenths. This is only a very approximate measure of the amount of arpeggiation in the music, of course.

     M-9 Repeated Notes: Fraction of melodic intervals that correspond to repeated notes.
     M-10 Chromatic Motion: Fraction of melodic intervals that correspond to a semitone.
     M-11 Stepwise Motion: Fraction of melodic intervals that correspond to a minor or major second.
     M-12 Melodic Thirds: Fraction of melodic intervals that are major or minor thirds.
     M-13 Melocid Perfect Fourths: Fraction of melodic intervals that are perfect fourths.
     M-14 Melodic Tritones: Fraction of melodic intervals that are tritones.
     M-15 Melodic Fifths: Fraction of melodic intervals that are perfect fifths.
     M-16 Melodic Sixths: Fraction of melodic intervals that are major or minor sixths.
     M-17 Melodic Sevenths: Fraction of melodic intervals that are major or minor sevenths.
     M-18 Melodic Octaves: Fraction of melodic intervals that are octaves.
     M-19 Melodic Large Intervals: Fraction of melodic intervals greater than one octave.
     M-20 Minor Major Melodic Third Ratio: Combined fraction of all melodic intervals that are minor thirds, divided by the combined fraction of all melodic intervals that are major thirds. Set to 0 if there are no melodic minor thirds or melodic major thirds.
     M-21 Melodic Embellishments: Fraction of all notes that are surrounded on both sides by MIDI Note Ons on the same MIDI channel that have durations at least three times as long as the central note. Set to 0 if there are no notes in the piece.
     M-22 Direction of Melodic Motion: Fraction of melodic intervals that are rising in pitch. Set to zero if no rising or falling melodic intervals are found.
     M-23 Average Length of Melodic Arcs: Average number of notes that separate melodic peaks and troughs. Similar assumptions are made in the calculation of this feature as for the Melodic Interval Histogram. Set to 0 if no melodic arcs are found.
     M-24 Average Interval Spanned by Melodic Arcs: Average melodic interval (in semitones) separating the top note of melodic peaks and the bottom note of adjacent melodic troughs. Similar assumptions are made in the calculation of this feature as for the Melodic Interval Histogram.
     M-25 Melodic Pitch Variety: Average number of notes that go by in a MIDI channel before a note's pitch is repeated (including the repeated note itself). This is calculated across each channel individually before being combined. Notes that occur simultaneously on the same MIDI tick are only counted as one note for the purpose of this calculation. Notes that do not recur after 16 notes in the same channel are not included in this calculation. Set to 0 if there are no qualifying repeated notes in the piece.


** CHORD FEATURES     

      C-1 Vertical Interval Histogram: A feature vector consisting of bin magnitudes of the vertical interval histogram described above. Each of the bins is associated with a different vertical pitch interval, and is labeled with the number of semitones in that corresponding interval. More specifically, these are numbered from 0 (a unison) to 127 (a vertical interval of 127 semitones). The magnitude of each bin is found by going through a recoding MIDI tick by MIDI tick and noting all vertical intervals that are sounding at each tick, as well as the MIDI velocities of the pair of notes involved in each vertical interval. The end result is a histogram that indicates which vertical intervals are present, and how significant these vertical intervals are relative to one another, with a weighting based on both MIDI velocity and the aggragated durations with which each interval is held throughout the piece. Finally, the histogram is normalized.
      C-2 Wrapped Vertical Interval Histogram: A feature vector consisting of bin magnitudes of the wrapped vertical interval histogram described above. Each of the bins is associated with a different vertical pitch interval, and is labeled with the number of semitones in that corresponding interval. More specifically, these are numbered from 0 (a unison) to 11 (a vertical interval of 11 semitones). The magnitude of each bin is found by going through a recoding MIDI tick by MIDI tick and noting all vertical intervals that are sounding at each tick, as well as the MIDI velocities of the pair of notes involved in each vertical interval. Intervals larger than 11 semitones are wrapped (e.g. an octave (12 semitones) is added to the bin for unisons (0 semitones)). The end result is a histogram that indicates which vertical intervals are present, and how significant these vertical intervals are relative to one another, with a weighting based on both MIDI velocity and the aggregated durations with which each interval is held throughout the piece. Finally, the histogram is normalized.
      C-3 Chord Type Histogram: A feature vector consisting of bin magnitudes of the chord type histogram described above. This is a normalized histogram that has bins labeled with types of chords (in the following order and with the indicated identifying codes): partial chords consisting of just two pitch classes [0], minor triads [1], major triads [2], diminished triads [3], augmented triads [4], other triads [5], minor seventh chords [6], dominant seventh chords [7], major seventh chords [8], other chords consisting of four pitch classes [9], and complex chords with more than four pitch classes [10]. The bin magnitudes are calculated by going through MIDI ticks one by one and incrementing the counter for the bin that corresponds to the chord, if any, that is present during each given tick; the result is that the chords in this histogram are weighted by the duration with which each chord is played. All inversions are treated as equivalent and octave doubling is ignored in the calculation of this histogram. Melodic behaviour is not considered, so arpeggios are not counted in this histogram.
      C-4 Average Number of Simultaneous Pitch Classes: Average number of different pitch classes sounding simultaneously. Rests are excluded from this calculation.
      C-5 Variability of Number of Simultaneous Pitch Classes: Standard deviation of the number of different pitch classes sounding simultaneously. Rests are excluded from this calculation.
      C-6 Average Number of Simultaneous Pitches: Average number of pitches sounding simultaneously. Rests are excluded from this calculation. Unisons are also excluded from this calculation, but octave multiples are included in it.
      C-7 Variability of Number of Simultaneous Pitches: Standard deviation of the number of pitches sounding simultaneously. Rests are excluded from this calculation. Unisons are also excluded from this calculation, but octave multiples are included in it.
      C-8 Most Common Vertical Interval: The interval in semitones corresponding to the wrapped vertical interval histogram bin with the highest magnitude.
      C-9 Second Most Common Vertical Interval: The interval in semitones corresponding to the wrapped vertical interval histogram bin with the second highest magnitude.
      C-10 Distance Between Two Most Common Vertical Intervals: The interval in semitones between the wrapped vertical interval histogram bins with the two most common vertical intervals.
      C-11 Prevalence of Most Common Vertical Interval: Fraction of vertical intervals on the wrapped vertical interval histogram corresponding to the most common vertical interval.
      C-12 Prevalence of Second Most Common Vertical Interval: Fraction of vertical intervals on the wrapped vertical interval histogram corresponding to the second most common vertical interval.
      C-13 Prevalence Ratio of Two Most Common Vertical Intervals: Ratio between the fraction of notes corresponding to the second most common vertical interval on the wrapped vertical interval histogram and the fraction of vertical intervals corresponding to the most common vertical interval. Set to 0 if either of these prevalences are 0.
      C-14 Vertical Unisons: Fraction of all vertical intervals that are unisons. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-15 Vertical Minor Seconds: Fraction of all wrapped vertical intervals that are minor seconds. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-16 Vertical Thirds: Fraction all wrapped vertical intervals that are minor or major thirds. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-17 Vertical Tritones: Fraction of all wrapped vertical intervals that are tritones. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-18 Vertical Perfect Fourths: Fraction of all wrapped vertical intervals that are perfect fourths. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-19 Vertical Perfect Fifths: Fraction of all wrapped vertical intervals that are perfect fifths. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-20 Vertical Sixths: Fraction all wrapped vertical intervals that are minor or major sixths. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-21 Vertical Sevenths: Fraction all wrapped vertical intervals that are minor or major sevenths. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-22 Vertical Octaves: Fraction of all wrapped vertical intervals that are octaves. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-23 Perfect Vertical Intervals: Fraction of all wrapped vertical intervals that are unisons, perfect fourths, perfect fifths or octaves. This is weighted by how long intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note).
      C-24 Vertical Dissonance Ratio: Ratio of all wrapped vertical intervals that are dissonant (2nds, tritones, and 7ths to all wrapped vertical intervals that are consonant (unisons, 3rds, 4ths, 5ths, 6ths, octaves). This is weighted by how long each of these intervals are held (e.g. an interval lasting a whole note will be weighted four times as strongly as an interval lasting a quarter note). Set to 0 if there are no dissonant vertical intervals or no consonant vertical intervals.
      C-25 Vertical Minor Third Prevalence: Fraction of the music by time where at least one wrapped vertical minor third is sounding (regardless of whatever other vertical intervals may or may not be sounding at the same time). Only that part of the music where one or more pitched notes is sounding is included in this calculation (rests and sections containing only unpitched notes are ignored).
      C-26 Vertical Major Third Prevalence: Fraction of the music by time where at least one wrapped vertical major third is sounding (regardless of whatever other vertical intervals may or may not be sounding at the same time). Only that part of the music where one or more pitched notes is sounding is included in this calculation (rests and sections containing only unpitched notes are ignored).
      C-27 Chord Duration: Average duration a chord in units of time corresponding to the duration of an idealized quarter note. A "chord" here is considered to stay the same as long as no new pitch classes are added, and no pitch classes are taken away. This "chord" may consist of any number of pitch classes, even only one. A "chord" is not considered to end if it is split by one or more rests (although the rests themselves are not counted in the duration of the "chord").
      C-28 Partial Chords: Fraction of simultaneously sounding pitch groups that consist of only two pitch classes. This is weighted by how long pitch groups are held (e.g. a pitch group lasting a whole note will be weighted four times as strongly as a pitch group lasting a quarter note).
      C-29 Standard Triads: Fraction of all simultaneously sounding pitch groups that are either major or minor triads. This is weighted by how long pitch groups are held (e.g. a pitch group lasting a whole note will be weighted four times as strongly as a pitch group lasting a quarter note).
      C-30 Diminished and Augmented Triads: Fraction of all simultaneously sounding pitch groups that are either diminished or augmented triads. This is weighted by how long pitch groups are held (e.g. a pitch group lasting a whole note will be weighted four times as strongly as a pitch group lasting a quarter note).
      C-31 Dominant Seventh Chords: Fraction of all simultaneously sounding pitch groups that are dominant seventh chords. This is weighted by how long pitch groups are held (e.g. a pitch group lasting a whole note will be weighted four times as strongly as a pitch group lasting a quarter note).
      C-32 Seventh Chords: Fraction of all simultaneously sounding pitch groups that are dominant seventh, major seventh or minor seventh chords. This is weighted by how long pitch groups are held (e.g. a pitch group lasting a whole note will be weighted four times as strongly as a pitch group lasting a quarter note).
      C-33 Non-Standard Chords: Fraction of all simultaneously sounding pitch groups that consist of more than two pitch classes yet are not major triads, are not minor triads and are not seventh chords. This is weighted by how long pitch groups are held (e.g. a pitch group lasting a whole note will be weighted four times as strongly as a pitch group lasting a quarter note).
      C-34 Complex Chords: Fraction of all simultaneously sounding pitch groups that contain more that four pitch classes. This is weighted by how long pitch groups are held (e.g. a pitch group lasting a whole note will be weighted four times as strongly as a pitch group lasting a quarter note).
      C-35 Minor Major Triad Ratio: The prevalence of minor triads divided by the prevalence of major triads. This is weighted by how long the chords are held (e.g. a chord lasting a whole note will be weighted four times as strongly as a chord lasting a quarter note). Set to 0 if there are no minor triads or if there are no major triads.




** extend bpf to also show bar-graphs - done in om7

	- make bpf miniview reflect mode in editor

** integrate with segmentation/analysis system:

  - manually/automatically set segments/phrases
  - feature extraction within segment/phrase
  - access data within segments

** melodic features

 - interval between successive notes
 - integrated over more than 2 notes, ie: 1-3, 1-N
 - autocorrelation, factor of repeatedness/patterns

** TODO check t-SNE, reduce multidimensional feature space to less dimensions 

** Remember

*** Check other systems [0/4]

    - [ ] Humdrum
    - [ ] jSymbolic
    - [ ] Rubato
    - [ ] Reisewissen : Witchcraft project, Utrecht : http://ismir2006.ismir.net/PAPERS/ISMIR0656_Paper.pdf
						      
						      [[file:~/ARTIKLER/Garbers_MIR_ISMIR0656_Paper_OM_HUMDRUM_RUBATO.pdf][file:~/ARTIKLER/Garbers_MIR_ISMIR0656_Paper_OM_HUMDRUM_RUBATO.pdf]]
